/* Crea database UNIBOSSS */
CREATE DATABASE IF NOT EXISTS UNIBOSSS;
USE UNIBOSSS;

/* Crea tabella CDS */
CREATE TABLE CDS (
	Nome VARCHAR(100) PRIMARY KEY
) ENGINE = INNODB;

/* Crea tabella CATEGORIA */
CREATE TABLE CATEGORIA (
	Sport VARCHAR(50) PRIMARY KEY,
	Regolamento TEXT,
	NumGiocatori INT,
	Foto VARCHAR(100) 
) ENGINE = INNODB;

/* Crea tabella UTENTE */
CREATE TABLE UTENTE (
	Username VARCHAR(50) PRIMARY KEY,
	Password VARCHAR(32),
	Nome VARCHAR(50),
	Cognome VARCHAR(50),
	Matricola VARCHAR(10) NOT NULL,
	AnnoNascita INT,
	LuogoNascita VARCHAR(50),
	Telefono VARCHAR(14),
	Foto VARCHAR(100), 
	NomeCdS VARCHAR(100),
	PartiteCalcio INT,
	PartiteBasket INT,
	PartiteTennis INT,
	FOREIGN KEY (NomeCdS) REFERENCES CDS(Nome) ON DELETE CASCADE ON UPDATE CASCADE	
) ENGINE = INNODB;

/* Crea tabella UP */
CREATE TABLE UP ( 
	UserUP VARCHAR(50) PRIMARY KEY,
	FOREIGN KEY (UserUP) REFERENCES UTENTE(Username) ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella US */
CREATE TABLE US (
	UserUS VARCHAR(50) PRIMARY KEY,
	FOREIGN KEY (UserUS) REFERENCES UTENTE(Username) ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella IMPIANTO */
CREATE TABLE IMPIANTO (
	NomeImpianto VARCHAR(50) PRIMARY KEY,
	Via VARCHAR(50),
	Telefono VARCHAR(13), 
	Email VARCHAR(50),
	Latitudine DECIMAL(9,7), 
	Longitudine DECIMAL(9,7) 
) ENGINE = INNODB;

/* Crea tabella ES */
CREATE TABLE ES (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Data DATE,
	Stato ENUM('APERTO', 'CHIUSO', 'ANNULLATO') DEFAULT 'APERTO',
	CategoriaSport VARCHAR(50),
	NomeImpianto VARCHAR(50),
	UserUP VARCHAR(50),
	FOREIGN KEY (CategoriaSport) REFERENCES CATEGORIA(Sport) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NomeImpianto) REFERENCES IMPIANTO(NomeImpianto) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UserUP) REFERENCES UP(UserUP) ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella POST */
CREATE TABLE POST (
	IdPost INT AUTO_INCREMENT PRIMARY KEY,
	Data DATE,
	Testo TEXT,
	Foto VARCHAR (100),
	UserUtente VARCHAR(50), 
	NomeCdS VARCHAR(100),
	CategoriaSport VARCHAR(50),
	FOREIGN KEY (UserUtente) REFERENCES UTENTE(Username) ON UPDATE CASCADE,
	FOREIGN KEY (NomeCdS) REFERENCES CDS(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CategoriaSport) REFERENCES CATEGORIA(Sport) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella ISCRIZIONE */
CREATE TABLE ISCRIZIONE (
	Data DATE,
	Stato ENUM('CONFERMATO', 'RIFIUTATO', 'IN ATTESA') DEFAULT 'IN ATTESA',
	UserUtente VARCHAR(50),
	IdEvento INT,
	UPApprovazione VARCHAR(50),
	PRIMARY KEY (UserUtente, IdEvento),
	FOREIGN KEY (UserUtente) REFERENCES UTENTE(Username) ON UPDATE CASCADE,
	FOREIGN KEY (IdEvento) REFERENCES ES(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UPApprovazione) REFERENCES UP(UserUP) ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella GIOCATORE */
CREATE TABLE GIOCATORE (
	UserUtente VARCHAR(50),
	IdEvento INT,
	PRIMARY KEY (UserUtente,IdEvento),
	FOREIGN KEY (UserUtente) REFERENCES ISCRIZIONE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdEvento) REFERENCES ISCRIZIONE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella ARBITRO */
CREATE TABLE ARBITRO (
	UserUtente VARCHAR(50),
	IdEvento INT,
	PRIMARY KEY (UserUtente,IdEvento),
	FOREIGN KEY (UserUtente) REFERENCES ISCRIZIONE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdEvento) REFERENCES ISCRIZIONE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella ESITO */
CREATE TABLE ESITO ( 
	IdEvento INT PRIMARY KEY,
	Data DATE,
	UserUP VARCHAR(50), 
	FOREIGN KEY (UserUP) REFERENCES UP(UserUP) ON UPDATE CASCADE,
	FOREIGN KEY (IdEvento) REFERENCES ES(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella SQUADRA */
CREATE TABLE SQUADRA (
	NomeSquadra VARCHAR(50) PRIMARY KEY	
) ENGINE = INNODB;

/* Crea tabella GRUPPO */
CREATE TABLE GRUPPO (
	IdEventoGruppo INT,
	NumeroPunti INT,
	NomeSquadra VARCHAR(50),
	PRIMARY KEY (IdEventoGruppo, NomeSquadra),
	FOREIGN KEY (IdEventoGruppo) REFERENCES ESITO(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NomeSquadra) REFERENCES SQUADRA(NomeSquadra) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella SINGOLO */
CREATE TABLE SINGOLO (
	IdEventoSingolo INT,
	UserGiocatore VARCHAR(50),
	IdEventoGiocatore INT,
	NumeroPunti INT,
	Durata TIME, 
	PRIMARY KEY (IdEventoSingolo, UserGiocatore, IdEventoGiocatore),
	FOREIGN KEY (IdEventoSingolo) REFERENCES ESITO(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UserGiocatore) REFERENCES GIOCATORE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdEventoGiocatore) REFERENCES GIOCATORE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;


/* Crea tabella COMPOSIZIONE  */
CREATE TABLE COMPOSIZIONE (
	Punti INT,
	NomeSquadra VARCHAR(50),
	UserGiocatore VARCHAR(50),
	IdEvento INT,
	PRIMARY KEY (NomeSquadra, UserGiocatore, IdEvento),
	FOREIGN KEY (NomeSquadra) REFERENCES SQUADRA(NomeSquadra) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UserGiocatore) REFERENCES GIOCATORE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,	
	FOREIGN KEY (IdEvento) REFERENCES GIOCATORE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

/* Crea tabella VALUTAZIONE  */
CREATE TABLE VALUTAZIONE (
	Data DATE,
	Voto INT,
	Commento TEXT,
	UserGiocatore VARCHAR(50),
	IdESGiocatore INT,
	UserValutante VARCHAR(50),
	IdESValutante INT,
	PRIMARY KEY (UserGiocatore, IdESGiocatore, UserValutante, IdESValutante),
	FOREIGN KEY (UserGiocatore) REFERENCES GIOCATORE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdESGiocatore) REFERENCES GIOCATORE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UserValutante) REFERENCES GIOCATORE(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdESValutante)	REFERENCES GIOCATORE(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;


/* Crea tabella ARBITRAGGIO */
CREATE TABLE ARBITRAGGIO (
	UserArbitro VARCHAR(50),
	IdESArbitro INT,
	IdEvento INT,
	PRIMARY KEY (UserArbitro, IdESArbitro, IdEvento),
	FOREIGN KEY (UserArbitro) REFERENCES ARBITRO(UserUtente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdESArbitro) REFERENCES ARBITRO(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdEvento) REFERENCES ESITO(IdEvento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB; 